add Depression-Language-Evaluation
Droidtown/LokiHub pull request #10
Opened 2021-09-17 10:04 UTC by Melody-Lin

Peter，我是沂萱，這是我跟Helena做的「憂鬱指數評估」。麻煩Peter確認，謝謝！

2021-09-18 02:05 UTC, Droidtown requested changes
請依評註說明做出相應的調整。謝謝。

2021-09-18 02:05 UTC, Droidtown commented on Depression-Language-Evaluation/ReadMe.md
> +## 憂鬱指數計算
請在 
> ## 憂鬱指數計算
這一項的下面，簡單說明一下這個 bot 的功能和設計目的。

2021-09-18 02:05 UTC, Droidtown commented on Depression-Language-Evaluation/ReadMe.md
> +<img src="https://github.com/Melody-Lin/Depression-Language-Evaluation/blob/main/Media/DLE.png" width="200"/>
Markdown 的圖片寫法是
![](image_url)
請調整一下。

2021-09-18 03:14 UTC, Melody-Lin commented on Depression-Language-Evaluation/ReadMe.md
> +<img src="https://github.com/Melody-Lin/Depression-Language-Evaluation/blob/main/Media/DLE.png" width="200"/>
peter, 可是如果我們用markdown的寫法好像就沒有辦法調整圖片的大小，所以圖片就會很大
但是用網路上的寫法又不能用 想請問peter有建議的markdown調整圖片的方法嗎？

2021-09-18 03:40 UTC, Droidtown commented on Depression-Language-Evaluation/ReadMe.md
> +<img src="https://github.com/Melody-Lin/Depression-Language-Evaluation/blob/main/Media/DLE.png" width="200"/>
那麼用現行的 html img 標籤或是把原圖縮小一點。兩個方法都可以哦。

2021-09-18 04:07 UTC, Melody-Lin commented on Depression-Language-Evaluation/ReadMe.md
> +<img src="https://github.com/Melody-Lin/Depression-Language-Evaluation/blob/main/Media/DLE.png" width="200"/>
好的 謝謝peter

2021-09-19 08:20 UTC, Droidtown commented on Depression-Language-Evaluation/ReadMe.md
> +    - 在LINE Developers上建立LINE Bot帳號
**LINE Developers** 這裡附個連結吧。:)

2021-09-19 08:21 UTC, Droidtown commented on Depression-Language-Evaluation/ReadMe.md
> +    - 在Heroku上建立相應帳號
同上，也給個 Heroku 的連結。如果同時還能附上它們的官方說明文件就更清楚了。

2021-09-19 12:49 UTC, Melody-Lin commented on Depression-Language-Evaluation/ReadMe.md
> +    - 在LINE Developers上建立LINE Bot帳號
這邊修改完畢，謝謝peter！

2021-09-19 12:49 UTC, Melody-Lin commented on Depression-Language-Evaluation/ReadMe.md
> +    - 在Heroku上建立相應帳號
這邊也修改完畢，謝謝peter！

2021-09-19 13:54 UTC, Droidtown approved these changes
Thanks. :)

2021-09-19 13:56 UTC, merged